# Cloudflare Worker configuration for Duct UI Search (Preview)
name = "starter-search-worker"
main = "worker.ts"
compatibility_date = "2024-04-03" # Required for RPC support

# KV namespace for search metadata
[[kv_namespaces]]
binding = "starter_search_metadata_preview"
id = "88649e0f5ed246cabd1a05204336355d"

# R2 bucket for search index storage
[[r2_buckets]]
bucket_name = "starter-search-index-preview"
binding = "starter_search_index_preview"

# Environment variables
# For local development, create a .env file:
# SEARCH_INDEX_AUTH_TOKEN=your-dev-token
#
# For preview deployment, set via:
# wrangler secret put SEARCH_INDEX_AUTH_TOKEN -c wrangler.preview.toml