# Cloudflare Worker configuration for Duct UI Search (Production)
name = "starter-search-worker"
main = "worker.ts"
compatibility_date = "2024-04-03" # Required for RPC support

# KV namespace for search metadata
[[kv_namespaces]]
binding = "SEARCH_METADATA"
id = "440b52d9d3f741fe826b1f7f5d41f0d5" # Production KV namespace ID

# R2 bucket for search index storage
[[r2_buckets]]
binding = "SEARCH_INDEX"
bucket_name = "starter-search-index-prod" # Production bucket name

# Environment variables
# Set via Cloudflare dashboard or:
# wrangler secret put SEARCH_INDEX_AUTH_TOKEN