# Add these configurations to your existing wrangler.toml
# or create a new wrangler.toml if you don't have one

name = "starter-worker"
main = "worker.ts"
compatibility_date = "2024-01-01"

# KV namespace for search metadata
[[kv_namespaces]]
binding = "SEARCH_METADATA"

# R2 bucket for search index storage
[[r2_buckets]]
binding = "SEARCH_INDEX"

# Environment variables
# Set SEARCH_INDEX_AUTH_TOKEN as a secret in Cloudflare dashboard:
# wrangler secret put SEARCH_INDEX_AUTH_TOKEN