packages:
  - packages/components
  - packages/core
  - packages/router
  - packages/cli
  - packages/demo
  - packages/starter
  - packages/mcp-server
  - packages/search-core
  - packages/client-search-provider
  - packages/cloudflare-search-provider